USE example;

DROP TABLE IF EXISTS T_Phone;
DROP TABLE IF EXISTS T_Userinformation;
DROP TABLE IF EXISTS T_Meeting;
DROP TABLE IF EXISTS User_Meeting;
DROP TABLE IF EXISTS T_USER;
DROP TABLE IF EXISTS T_ROOM;

CREATE TABLE T_User (F_ID INT PRIMARY KEY AUTO_INCREMENT, F_Login VARCHAR(40),  F_Name VARCHAR(40)  );
CREATE TABLE T_Phone (F_ID INT PRIMARY KEY AUTO_INCREMENT, F_Phone VARCHAR(20), FK_UserID INT(5),  FOREIGN KEY (FK_UserID) REFERENCES T_USER(F_ID) ON DELETE CASCADE);
CREATE TABLE T_Userinformation (F_ID INT PRIMARY KEY AUTO_INCREMENT, F_Address VARCHAR(100), FOREIGN KEY (F_ID) REFERENCES T_USER(F_ID) ON DELETE CASCADE );
CREATE TABLE T_Meeting (F_ID INT PRIMARY KEY AUTO_INCREMENT, F_MeetingName VARCHAR(50));
CREATE TABLE User_Meeting (FK_User INT(5), FK_Meeting INT(5),
  CONSTRAINT  FK_User FOREIGN KEY (FK_User) REFERENCES T_User(F_ID),
  CONSTRAINT  FK_Meeting FOREIGN KEY (FK_Meeting) REFERENCES T_Meeting(F_ID) ON DELETE CASCADE);
CREATE TABLE T_Room(F_ID INT PRIMARY KEY AUTO_INCREMENT, F_RoomNumber INT(5), F_RoomName VARCHAR(40), FOREIGN KEY (F_ID) REFERENCES T_Meeting(F_ID) ON DELETE CASCADE );
